-- =====================================================================
-- LIMPAR VENDAS DE TESTE + NÚMERO CURTO DE PEDIDO
-- Rodar no Supabase > SQL Editor (projeto atadiesel / PRODUCTION)
-- ATENÇÃO: a PARTE 1 apaga TODOS os pedidos definitivamente.
-- =====================================================================

-- ---------------------------------------------------------------------
-- PARTE 0 (opcional): conferir o que será apagado
-- ---------------------------------------------------------------------
select 'orders' as tabela, count(*) from public.orders
union all select 'order_items', count(*) from public.order_items
union all select 'order_events', count(*) from public.order_events
union all select 'order_timeline', count(*) from public.order_timeline
union all select 'order_chat_messages', count(*) from public.order_chat_messages
union all select 'driver_locations', count(*) from public.driver_locations;

-- ---------------------------------------------------------------------
-- PARTE 1: apagar todas as vendas (tabelas filhas primeiro)
-- Se alguma outra tabela referenciar orders, o commit falha e nada é apagado.
-- ---------------------------------------------------------------------
begin;
  delete from public.order_chat_messages;
  delete from public.order_timeline;
  delete from public.order_events;
  delete from public.order_items;
  delete from public.driver_locations where order_id is not null;
  delete from public.orders;
commit;

-- ---------------------------------------------------------------------
-- PARTE 2: número sequencial curto do pedido (#0001, #0002, ...)
-- O painel já usa esta coluna automaticamente quando ela existir.
-- ---------------------------------------------------------------------
alter table public.orders
  add column if not exists order_number bigint generated by default as identity;

create unique index if not exists orders_order_number_key on public.orders (order_number);

-- Recomeça a numeração do 1 (só faz sentido com a tabela vazia)
alter table public.orders alter column order_number restart with 1;
